---

- name: install packages
  package: 
    name: "{{item}}"
    state: "{{ libvirt_state }}"
  with_items: "{{ libvirt_packages[ansible_distribution_major_version] }}"

- name: activate ipv4 forwarding
  sysctl:
    name: "net.ipv4.ip_forward"
    value: 1
    state: present
    reload: yes

- name: "deactivate ipv4 redirects on {{libvirt_rootserver_ifName}}"
  sysctl:
    name: "net.ipv4.conf.{{libvirt_rootserver_ifName}}.send_redirects"
    value: 0
    state: present
    reload: yes
